### ISSUE TITLE
Suggested Improvements in Voice Recognition Performance

### ISSUE THREAD

**Issue by Crix-gmu** [Crix-gmu/MPC-voice#4]
Hi, thanks for supporting the MPC-voice project. I noticed that the performance of the current version of voice recognition degrades when dealing with audio with high background noise. In order to further improve the recognition accuracy, I suggest adding noise reduction processing in the feature extraction phase. Specifically, try the following methods:
Introduce Spectral Subtraction technique for preprocessing.
Add processing of MFCC (Mel Frequency Cepstrum Coefficient) in the feature extraction process.
Consider using more advanced deep learning models, such as CNN or RNN, for feature extraction and recognition.
I hope to discuss and improve this feature with you. If there are other better methods, feel free to share them as well!

**Comment by LeGai325** [comment]
Hello,

Thank you for your suggestions to improve the voiceprint recognition system. Implementing noise reduction techniques such as Spectral Subtraction could indeed enhance performance. Additionally, incorporating advanced models like CNN or RNN for feature extraction sounds promising.

I'd like to suggest experimenting with the Wiener filter for noise reduction as well, which has shown effectiveness in similar applications. Collaborating on these improvements would be beneficial. Looking forward to further discussions and contributions.

Best regards,
